vich_uploader:
    db_driver: orm

    mappings:
        livres:
            uri_prefix: /images/livres
            upload_destination: '%kernel.project_dir%/public/images/livres'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        rencontres:
            uri_prefix: /images/rencontres
            upload_destination: '%kernel.project_dir%/public/images/rencontres'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        agenda:
            uri_prefix: /images/agenda
            upload_destination: '%kernel.project_dir%/public/images/agenda'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
   
